spring:
  datasource:
    url: jdbc:mysql://localhost:3306/instagram_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # 앱 시작 시 테이블 자동 생성
    show-sql: true            # 실행 SQL 콘솔에 출력
    properties:
      hibernate:
        format_sql: true

  security:
    enabled: false            # TODO: Security 활성화

server:
  port: 8080